Debug values.yaml location

diff --git a/.github/workflows/helm-ci-cd.yml b/.github/workflows/helm-ci-cd.yml
--- a/.github/workflows/helm-ci-cd.yml
+++ b/.github/workflows/helm-ci-cd.yml
@@ -97,6 +97,13 @@ jobs:
           curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
           helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
           helm repo update
+      
+      # - name: Debug: Print working directory and files
+      #   run: |
+      #     cd ${{ github.workspace }}
+      #     pwd
+      #     ls -la
+      #     ls -la values.yaml || echo "values.yaml not found"
 
       - name: Deploy OpenTelemetry Demo using Helm
         id: helm_upgrade
@@ -105,6 +112,9 @@ jobs:
           KUBECONFIG: kubeconfig
         run: |
           cd ${{ github.workspace }}
+          echo "🧪 Listing directory to confirm values.yaml presence"
+          ls -la
+          ls -la values.yaml
           helm upgrade --install ${{ env.RELEASE_NAME }} open-telemetry/opentelemetry-demo \
             --namespace ${{ env.NAMESPACE }} --create-namespace \
             -f values.yaml
